openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/admin/travels:
    post:
      summary: 'pOST Travel'
      operationId: pOSTTravel
      description: 'Create a new Travel record.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 9c55789a-07ea-4a87-b3ac-424a48ebdf6b
                    name: Main-travel-update
                    slug: travel-2
                    description: 'For testing parameter'
                    number_of_days: '10'
                    number_of_nights: 9
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 9c55789a-07ea-4a87-b3ac-424a48ebdf6b
                      name:
                        type: string
                        example: Main-travel-update
                      slug:
                        type: string
                        example: travel-2
                      description:
                        type: string
                        example: 'For testing parameter'
                      number_of_days:
                        type: string
                        example: '10'
                      number_of_nights:
                        type: integer
                        example: 9
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  errors:
                    name:
                      - 'The name has already been taken.'
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name has already been taken.'
                        items:
                          type: string
      tags:
        - 'Admin endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_public:
                  type: boolean
                  description: ''
                  example: false
                name:
                  type: string
                  description: ''
                  example: sapiente
                description:
                  type: string
                  description: ''
                  example: eaque
                number_of_days:
                  type: integer
                  description: ''
                  example: 20
              required:
                - name
                - description
                - number_of_days
  '/api/v1/admin/travels/{travel_id}':
    put:
      summary: ''
      operationId: putApiV1AdminTravelsTravel_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Admin endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_public:
                  type: boolean
                  description: ''
                  example: false
                name:
                  type: string
                  description: ''
                  example: qui
                description:
                  type: string
                  description: ''
                  example: ab
                number_of_days:
                  type: integer
                  description: ''
                  example: 5
              required:
                - name
                - description
                - number_of_days
      security: []
    parameters:
      -
        in: path
        name: travel_id
        description: 'The ID of the travel.'
        example: 9c522b13-8593-4a3d-9dce-c12fec659912
        required: true
        schema:
          type: string
  /api/v1/user:
    get:
      summary: ''
      operationId: getApiV1User
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/travels:
    get:
      summary: ''
      operationId: getApiV1Travels
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 9c5233bf-b005-4b5b-8e08-a1719d804f30
                      name: 'Travel 1'
                      slug: travel-1-2
                      description: 'For test only'
                      number_of_days: 14
                      number_of_nights: 13
                    -
                      id: 9c55789a-07ea-4a87-b3ac-424a48ebdf6b
                      name: Main-travel-update
                      slug: travel-2
                      description: 'For testing parameter'
                      number_of_days: 10
                      number_of_nights: 9
                    -
                      id: 9c5578ed-2c74-42d5-8aee-79bb05ab64e0
                      name: 'Travel 2'
                      slug: travel-2-2
                      description: 'For test only'
                      number_of_days: 7
                      number_of_nights: 6
                    -
                      id: 9c5578f6-ad89-4233-bf98-3a7b4c34b74f
                      name: 'Travel 2'
                      slug: travel-2-3
                      description: 'For test only'
                      number_of_days: 3
                      number_of_nights: 2
                    -
                      id: 9c665cf0-a2eb-4b81-85c1-3d24430a3820
                      name: Main-travel
                      slug: main-travel
                      description: 'For testing parameter'
                      number_of_days: 10
                      number_of_nights: 9
                  links:
                    first: 'http://localhost/api/v1/travels?page=1'
                    last: 'http://localhost/api/v1/travels?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/v1/travels?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/v1/travels'
                    per_page: 15
                    to: 5
                    total: 5
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 9c5233bf-b005-4b5b-8e08-a1719d804f30
                        name: 'Travel 1'
                        slug: travel-1-2
                        description: 'For test only'
                        number_of_days: 14
                        number_of_nights: 13
                      -
                        id: 9c55789a-07ea-4a87-b3ac-424a48ebdf6b
                        name: Main-travel-update
                        slug: travel-2
                        description: 'For testing parameter'
                        number_of_days: 10
                        number_of_nights: 9
                      -
                        id: 9c5578ed-2c74-42d5-8aee-79bb05ab64e0
                        name: 'Travel 2'
                        slug: travel-2-2
                        description: 'For test only'
                        number_of_days: 7
                        number_of_nights: 6
                      -
                        id: 9c5578f6-ad89-4233-bf98-3a7b4c34b74f
                        name: 'Travel 2'
                        slug: travel-2-3
                        description: 'For test only'
                        number_of_days: 3
                        number_of_nights: 2
                      -
                        id: 9c665cf0-a2eb-4b81-85c1-3d24430a3820
                        name: Main-travel
                        slug: main-travel
                        description: 'For testing parameter'
                        number_of_days: 10
                        number_of_nights: 9
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 9c5233bf-b005-4b5b-8e08-a1719d804f30
                        name:
                          type: string
                          example: 'Travel 1'
                        slug:
                          type: string
                          example: travel-1-2
                        description:
                          type: string
                          example: 'For test only'
                        number_of_days:
                          type: integer
                          example: 14
                        number_of_nights:
                          type: integer
                          example: 13
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/v1/travels?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/v1/travels?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/v1/travels?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/v1/travels'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: integer
                        example: 5
                      total:
                        type: integer
                        example: 5
      tags:
        - Endpoints
      security: []
  '/api/v1/travels/{travel_slug}/tours':
    get:
      summary: ''
      operationId: getApiV1TravelsTravel_slugTours
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Travel] 9c522b13-8593-4a3d-9dce-c12fec659912'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Travel] 9c522b13-8593-4a3d-9dce-c12fec659912'
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                priceFrom:
                  type: number
                  description: ''
                  example: 7.0
                priceTo:
                  type: number
                  description: ''
                  example: 1830193.0
                dateFrom:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-07-04T02:53:15'
                dateTo:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-07-04T02:53:15'
                sortBy:
                  type: string
                  description: ''
                  example: price
                  enum:
                    - price
                sortOrder:
                  type: string
                  description: ''
                  example: desc
                  enum:
                    - asc
                    - desc
      security: []
    parameters:
      -
        in: path
        name: travel_slug
        description: 'The slug of the travel.'
        example: 9c522b13-8593-4a3d-9dce-c12fec659912
        required: true
        schema:
          type: string
  '/api/v1/admin/travels/{travel_id}/tours':
    post:
      summary: ''
      operationId: postApiV1AdminTravelsTravel_idTours
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: eligendi
                starting_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-07-04T02:53:15'
                ending_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>starting_date</code>.'
                  example: '2063-11-27'
                price:
                  type: number
                  description: ''
                  example: 0.0
              required:
                - name
                - starting_date
                - ending_date
                - price
      security: []
    parameters:
      -
        in: path
        name: travel_id
        description: 'The ID of the travel.'
        example: 9c522b13-8593-4a3d-9dce-c12fec659912
        required: true
        schema:
          type: string
  /api/v1/login:
    post:
      summary: 'Handle the incoming request.'
      operationId: handleTheIncomingRequest
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ubeer@example.com
                password:
                  type: string
                  description: ''
                  example: '[Q3$l"]='
              required:
                - email
                - password
      security: []
tags:
  -
    name: 'Admin endpoints'
    description: ''
  -
    name: Endpoints
    description: ''
